### ISSUE TITLE
NO CRANKYS ALLOWED

### ISSUE THREAD

**Issue by averagedeveloper2k** [averagedeveloper2k/ToontownOnline#1]

**Comment by toonjoey** [comment]
Toontown Ultimate Adventure is a Toontown server based of Disney's now closed MMO game "Toontown Online" with brand new features and whole fun exploring.
​
Toontown Ultimate Adventure are from the creators of Toontown HD and they wanted to make it brand new and changed the whole design into a great server that everyone have seen.
